### ISSUE TITLE
Linux: Supporting the XDG Base Directory Specification

### ISSUE THREAD

**Issue by goteksc** [MrAlex94/Waterfox#1542]
Would it be possible to work towards supporting the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) [(Summary on the arch wiki)](https://wiki.archlinux.org/index.php/XDG_Base_Directory)?

Even just allowing to set an environment variable like $WATERFOX_CONFIG_DIR or something like that would help.

Unfortunately it's not likely that mozilla would add this support anytime soon, as the conversation around it is going on for [16 years](https://bugzilla.mozilla.org/show_bug.cgi?id=259356) without bearing fruit.

**Comment by MrAlex94** [comment]
Sounds interesting! Have assigned it, will try add it to the v78 feature list.

**Comment by magnus-ISU** [comment]
Any updates on this?

Also, found something interesting; waterfox (and I assume firefox) has the ability to set custom directories for your profiles. Run waterfox with the `-P` option, and you can create a profile with a custom directory already. This means that (probably, I don't claim to know or use all the features which might create weird files) the only hardcoded paths that need to be fixed are:
./waterfox/Crash\\ Reports/*
./waterfox/Pending\\ Pings/ [empty for me]
./waterfox/profiles.ini
./waterfox/installs.ini
./mozilla/native-messaging-hosts/*
./mozilla/extensions/ [empty for me despite me having 7 browser extensions installed]
./mozilla/systemextensionsdev/ [empty for me]

I think that profiles.ini and installs.ini should go in $XDG_CONFIG_HOME/waterfox, as well as maybe native-messaging-hosts. Otherwise if there is ambiguity I would put them in $XDG_DATA_HOME/waterfox. It already has a folder in $XDG_CACHE_HOME. Not sure if a seperate directory is needed for mozilla as .mozilla currently contains almost nothing for me.

**Comment by magnus-ISU** [comment]
It seems this has already been implemented by mozilla and has just been dead for 2 years in their nightmare of a review process: https://phabricator.services.mozilla.com/D6995#3176429
(it wouldn't move some files to XDG_CONFIG_HOME and others to XDG_DATA_HOME, though)
Am currently compiling waterfox with some of the changes described there, will update if it works

**Comment by magnus-ISU** [comment]
There is almost an easy fix actually (almost, see end). The only change needed is at line 1440 in toolkit/xre/nsXREDirProvider.cpp:
```
  char* homeDir = getenv("WATERFOX_DATA_DIR");
  if (!homeDir || !*homeDir) homeDir = getenv("XDG_DATA_HOME");
  if (!homeDir || !*homeDir) homeDir = getenv("HOME");
  if (!homeDir || !*homeDir) return NS_ERROR_FAILURE;
```
If it is important to avoid breaking previous people's configurations when they update (assuming they have defined XDG_DATA_HOME, and only until they run `mv .waterfox .mozilla $XDG_DATA_HOME` or `echo 'export WATERFOX_DATA_DIR="$HOME"' >> .bash_profile`, which I think is not too much to ask, but I have to remember a lot of people are not developers or even know what this spec is) then we can just remove the second line and force people to specify the directory manually if they want to spring clean their ~ (while that doesn't follow the spec, and leads to a lot of environmental variables being created if every program does it, I agree with GotekSC that it is acceptable).
The only problem with this is that it doesn't really follow the specification fully because certain configuration files are still stored in DATA_HOME rather than CONFIG_HOME, however I don't understand enough about firefox to be able to change that. As for why I chose DATA_HOME over CONFIG_HOME, the dudes over at mozilla have been arguing back and forth for at least 10 years about which they should choose, but I think it should be DATA because I have about 250 files in my .config and 200 of them are from gimp, and of the others I've manually edited over half of them probably. I have over 17000 files and subdirectories in my .local/share. Also, crash reports are not configuration files

There is still a problem which this does not fix: Waterfox is creating a .waterfox in my $HOME when I start the program. This directory is not touched afterwards, so for now I created a little bash script to launch waterfox, sleep 1 second and remove it. Still, would want to fix this before releasing anything. Also, I have only tested this on my computer so I have no idea if it would break like an android phone or something. I imagine that is part of the reason why mozilla hasn't done this 2-line change.

EDIT: I lied, this isn't a complete fix as I can't install extensions easily through mozilla's website anymore. Any ideas why that might be?
EDIT2: I lied about lying, after running ./mach package downloading extensions works fine.

EDIT3: I have made similar changes in both `toolkit/crashreporter/client/crashreporter_gtk_common.cpp` and `xpcom/io/SpecialSystemDirectory.cpp` (the only other two files with a getenv("HOME") related to linux I think), but a folder is still created in my $HOME. It seems likely to me that some non-cpp code is responsible for this - how would I go about finding where that code is? I know next to nothing about javascript or what it is doing in Waterfox and even less about Rust, so I'm kind of stuck.

**Comment by magnus-ISU** [comment]
Setting ~'s permissions to 500 prevents it from being created but does not produce any error messages - really stuck here.

**Comment by MrAlex94** [comment]
Dupe - has been fixed in next gen of Waterfox.

**Comment by Lassebq** [comment]
Does it require an environment variable? I have just started using Waterfox (G5.1.8) and it still creates ~/.waterfox

**Comment by Lassebq** [comment]
So I noticed that #2747 is open. Does this mean it's not actually fixed?

**Comment by MrAlex94** [comment]
It _was_ fixed, but caused issues with users upgrading to the the G4, so it was backed out again. Kept that issue open to track it and hopefully implement fully and properly.
