### ISSUE TITLE
[Waterfox Classic 2021.01] Some addons has been disabled and I can´t reactivate them

### ISSUE THREAD

**Issue by Killogy** [MrAlex94/Waterfox#1919]
Before latest Waterfox update I was running some addons without issues, they are working properly.

Latest Waterfox update ran a compatibility addons check and some addons has been disabled despite they are working properly previously. Waterfox is not allowing me to reactivate them.

Under Addons, shows sentence these "are not compatible with Waterfox 56.3", but they are working properly and are not disabled under Waterfox 2020.12.

* Augmented Steam 1.4.8 (Installs properly from addons.mozilla and every addon feature is working properly under Waterfox 2020.12)

https://addons.mozilla.org/es/firefox/addon/enhanced-steam-an-itad-fork/

* Open With 7.2.2 (Refuses to install from addons.mozilla but I rebuilded it by changing min version number, and then Installs and is working properly under Waterfox 2020.12)

https://addons.mozilla.org/es/firefox/addon/open-with/

* Temporary Containers 0.103 (Installs properly from addons.mozilla and every addon feature is working properly under Waterfox 2020.12)

https://addons.mozilla.org/es/firefox/addon/temporary-containers/

Now I reinstalled Waterfox 2020.12 because I need these addons and because Waterfox 2021.01 is not allowing me to reactivate them.

Is there any way to reactivate them or disable this compatibility addon check ?

xpinstall.signatures.required is false.
extensions.strictCompatibility is false

P.S: I added extensions.checkCompatibility.56.4 false and now these addons have reactivated.

**Comment by LeeBinder** [comment]
Great, thanks. Confirmed - via `about:config`, adding `extensions.checkCompatibility.56.4` as `boolean` -> `false`  reactivated all disabled XTs again immediately :)

@MrAlex94 looks as if best when pushing a quick 2021.01.1 update with this fix

**Comment by decembre** [comment]
Same for me with these addon:
<a href="https://addons.mozilla.org/fr/firefox/addon/clippings/">Clippings par AE Creations</a>
And "Make Link" by RoryParle  (not listed now in The firefox addon page)

I can have them working only if i enable the old addon addon (too not listed now in The firefox addon page):
**checkCompatibility by Kris Maglione - alike3**

**Comment by MrAlex94** [comment]
Sorry about that, been a while since I've bumped the gecko version! Will add it in a supplementary update.

**Comment by LeeBinder** [comment]
superb (can't help Geckos producing poop, seems part of their life mission)

**Comment by MrAlex94** [comment]
2021.01.1 has now been released to fix this :-)

**Comment by decembre** [comment]
Tested the last update:

Not working for these addons i notice before.
And as i said, the only thing working is to use this (old) addon:
checkCompatibility by Kris Maglione - alike3

**Comment by LeeBinder** [comment]
Thank you Alex for the super-quick fix, all fine here now with the latest update even after removing `extensions.checkCompatibility.56.4` in 2020.01 before installing 2020.01.1, which as supposed adds the string automatically.

@decembre I cannot second your issues. Here, even without `checkCompatibility` by Kris Maglione:

![Bildschirmfoto 2021-01-28 um 19 40 40](https://user-images.githubusercontent.com/39203497/106184612-1469b400-61a2-11eb-86b2-c66d8954de75.jpg)
![Bildschirmfoto 2021-01-28 um 19 42 39](https://user-images.githubusercontent.com/39203497/106184665-25b2c080-61a2-11eb-8f7c-e6c8452ed2d8.jpg)
and
![Bildschirmfoto 2021-01-28 um 19 44 57](https://user-images.githubusercontent.com/39203497/106184697-2f3c2880-61a2-11eb-998a-859db46108c6.jpg)
![Bildschirmfoto 2021-01-28 um 19 46 17](https://user-images.githubusercontent.com/39203497/106184720-35320980-61a2-11eb-88df-5661911cf267.jpg)

**Comment by decembre** [comment]
That's strange ...
Installing 2020.01.1, on my principal profile, i have the same problem:
These addons don't work ( after restart and disable the addon "checkCompatibility2 by Kris Maglione - alike3 ").

By example, for The Clipping addon, it is not possible to install or reinstall it:
![WAT classic - Clippin Addon PB - 2021-01-28_202409](https://user-images.githubusercontent.com/868778/106189772-053a3480-61a9-11eb-89b1-b62fb3bbc648.jpg)
![WAT Classic 56 4 - PB Clipping - 2021-01-28_202210](https://user-images.githubusercontent.com/868778/106190158-8db8d500-61a9-11eb-8c6c-97138658b414.jpg)
![WAT classic - Clippin Addon PB - LIGHTING - 2021-01-28_202510](https://user-images.githubusercontent.com/868778/106190276-bb058300-61a9-11eb-96e4-5b6cc54d5a03.jpg)

But on another profile, they work fine.

My about:config for both profiles
xpinstall.signatures.required is false.
extensions.strictCompatibility is false
So, i don't understand where is the problem:
before the update, all was OK.
What's can be wrong ?
What i can do?

**Comment by LeeBinder** [comment]
- right click onto 'Ajouter à Firefox' and copy the link into the clipboard
- paste it into the address bar
- remove the .xpi
- press enter
- go to about:addons
- **REFRESH THE ADDON PAGE !!!**

**Comment by decembre** [comment]
Done , without luck....
Normally i drag the disable "install" button into the adressbar to install some "disbale" addon and that work.

I continue to test this bad profile (after backup it...):
Now i remove some addons which i think can interfere.
At this time, with no progress (each time i reload waterfox)

The multi processor is disable.
In my about config, i see these entry (maybe it's related?):

![WAT Classic - PB ADDON - about config A - Profile PB - 2021-01-28_212422](https://user-images.githubusercontent.com/868778/106198526-703d3880-61b4-11eb-8526-4d5eadd9a269.jpg)
![WAT Classic - PB ADDON - about config B - Profile PB - 2021-01-28_212422](https://user-images.githubusercontent.com/868778/106198530-73382900-61b4-11eb-91c8-7d7caca16633.jpg)

After my clean:
![WAt Classic - aboutConfig - C after desintall some addon - 2021-01-28_220424](https://user-images.githubusercontent.com/868778/106199150-53553500-61b5-11eb-9976-4142532d823f.jpg)

**Comment by LeeBinder** [comment]
possibly. I've run into similar issues numerous times. Yes, always disable Extensions one-by-one and keep on testing.

If an issue persists even with all XTs disabled apart from the one you're trying to debug/ revive: quit WF, go to your profile folder, sort by date, remove a bunch of recent files/ folders, make notes of your moves, restart WF. Repeat until you've found the culprit file(s) and Google what to do 👍

**Comment by decembre** [comment]
Thanks for the help ....

A lot of work as usual!
Maybe i need, one more time, to rebuild my fresh main profile.

It's damn difficult to keep something working yet.

Before i used only Firefox.
Now i use 3 different browser (Firefox Quantum, Waterfox, Chrome) and many profiles for testing.
And for each, i need to remember what special tweak i have made.

Only because Firefox break their compatibility with their own legacy extension!
Now they have lost many user...
That's sad.

About the very last Update of Waterfox:
At least i don't need now to use an user agent switcher for yahoo mail or Google Mail.
Many thanks to Alex!
;-)

**Comment by LeeBinder** [comment]
Only 3? Lucky you are .. ;)

I always zip up a backup of my profile every once in a while and keep each. That way I can always revert to an older backup for debugging. Sometimes everything is back to normal after updating Extensions + re-sync PWs.
