### ISSUE TITLE
Cannot Run G4 Beta

### ISSUE THREAD

**Issue by JodyThornton** [MrAlex94/Waterfox#2282]
### What happened?

I tried installing the G4 early build off of GitHub, but it won't run as it says vcruntime140_1.dll is missing. So I also installed the Visual C++ 2015 Runtime (and I used the x64 version). Now I get a module error in mozglue.dll. That file is present in the Waterfox program folder.

I'm on Windows 8. I tried to upgrade, and use a new profile. Either case, it doesn't run past this error.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Windows

**Comment by ghost** [comment]
for me the same ??

**Comment by wbak1102** [comment]
and also the same for me.

**Comment by MrAlex94** [comment]
Should be fixed with this commit: https://github.com/WaterfoxCo/Waterfox/commit/283f6e05e4558eb51f693c77d47ae541c7d326a9

You can grab the updated binaries once the build completes.

**Comment by MrAlex94** [comment]
Waterfox G4.0.0b2 binaries are now available as well, it should have picked up all the correct redist files now, including the one that was missing for you all: https://github.com/WaterfoxCo/Waterfox/runs/3792386835?check_suite_focus=true#step:11:88

**Comment by JodyThornton** [comment]
Nope - it still does not run on Windows 8.  Waterfox brings up this APPCRASH error in Windows and asks to close.

**Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	waterfox.exe
  Application Version:	91.2.0.7947
  Application Timestamp:	615b1802
  Fault Module Name:	mozglue.dll
  Fault Module Version:	91.2.0.7947
  Fault Module Timestamp:	615b17fe
  Exception Code:	c000001d
  Exception Offset:	000000000000703f
  OS Version:	6.2.9200.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	4cba
  Additional Information 2:	4cbad84648a73687519f09f60ea37422
  Additional Information 3:	ea6e
  Additional Information 4:	ea6ef055bb982288e2b2a9c9fe7aaa80

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt**

**Comment by MrAlex94** [comment]
That's a different error completely.

What processor do you have?

**Comment by JodyThornton** [comment]
I have dual Xeon Quad Core processors at 3.20 GHz (they are x5482)
It's an HP xw8600 Worstation

**Comment by JodyThornton** [comment]
One thing Alex - I've set my installation up a s single process.   Should I enable Electrolysis?

**Comment by MrAlex94** [comment]
Ah looks like your CPU doesn't support `SSE4.2` surprisingly! Waterfox G4 final release will most likely have that as a requirement.

It brings quite a good performance improvement for the majority of users, so I will be looking into if dropping down to `SSE4.1` is an  acceptable performance loss

**Comment by JodyThornton** [comment]
Wow!  I can't believe I'm already at the stage where comparability issues arise.  Is this also the case for Firefox 91 ESR?
I'll be looking forward to see what happens.

**Comment by MrAlex94** [comment]
Firefox probably won't top up this kind of hardware requirement for a few more years at least. Looking at various hardware stats that are publicly available such as the [steam hardware survey](https://store.steampowered.com/hwsurvey) (which we can imagine the Waterfox user base is similar to) about 98.45% of systems support SSE4.2.

I'd love to get Waterfox back on track performance wise, and it seems a good trade off. I do appreciate it's not pleasant for those who don't have processors that support it - so still testing this out.

**Comment by MrAlex94** [comment]
Will close this for now, until more discovery for SSE4.2 support happens.
