### ISSUE TITLE
Automatic updates doesn't work properly

### ISSUE THREAD

**Issue by Patrxgt** [MrAlex94/Waterfox#2729]
### What happened?

When browser tried to auto update itself from G4.1.2.1 to G4.1.3.1, it failed with unknown reason and forced me to update it manually. I've tried to restart the browser and disable all extensions, but it didn't worked out. It seams like browser can recognize, that newer version is available, but fails to find proper link to download the newest version (same for update changelogs).

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by adamp01** [comment]
Thanks for raising. Looks to be an issue with credentials to move files on cdn.waterfox.net. We are looking into a fix for this now.

**Comment by adamp01** [comment]
Should now be resolved.

**Comment by Patrxgt** [comment]
Weeeell...
![obraz](https://user-images.githubusercontent.com/62941214/176547386-0aaa801a-fee9-4707-af30-9d99fb623f4b.png)
It isn't resolved as far as I can see.
