### ISSUE TITLE
Website Appearance "Dark" Preference not applying to Google Search properly

### ISSUE THREAD

**Issue by IdrisQe** [MrAlex94/Waterfox#2929]
### What happened?

Using the "dark" website appearance option, most pages will correctly load the dark theme on first open, but this isn't the case with Google, despite it supporting browser/system detected dark mode. If you don't remain signed in to Google, and have Waterfox set to delete cookies on exit, the next time you load into Google Search from a fresh browser open, it will be the blinding white theme until you either perform a search or refresh the page, at which point Waterfox's dark preference will apply correctly.

I currently have to use a hacky script to work around this by automatically "clicking" the Dark Mode button in Google Search's settings after the page loads, but that still flashbangs me since it can't work until the page has *fully* loaded.

Is there a way this could be fixed on Waterfox's end? Since I doubt Google will ever do anything about it.

I'm currently on G5.1 - by the way unrelated but you should probably update the "Version" dropdown in the bug report template as the only options are G4, which is outdated, and Other.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by daddyattitude** [comment]
Amazing this has NOT been addressed in over a year.
I have duplicated the WHITE PAGE effect with the following search engines.
Yahoo
Google
Bing

Search Engines NOT changing from Dark Mode
Duckduckgo
Startpage
Ecosia
Qwant

YouTube will Flash White then go Dark mode.

SURPRISINGLY,
Your website for WaterFox - Waterfox.net - comes in a BLINDING Blue and White while Dark Mode is ENABLED.

I am currently using the theme called, "Dark 1.2". In the past it worked correctly. It would be nice to know if this was a WATERFOX issue or an issue with the Theme. Adding 8 screenshots seems redundant.
Thank you for your time.

**Comment by daddyattitude** [comment]
I added this comment, rather than start a new thread. Starting a new thread seemed redundant.

**Comment by IdrisQe** [comment]
I'm disappointed this is still occuring too, yeah. Even using an addon to make Google dark instead, the logo still shows the (often blinding, depending on day-by-day logo) light mode logo until I refresh the page, which kind of defeats the whole purpose of using such addons if I still get eye strain from contrast issues. Could (and might) just replace the logo entirely using a userstyle or something, but doesn't get to the root of the problem still.
