### ISSUE TITLE
I can't access the Twitch website 

### ISSUE THREAD

**Issue by FacundoPV** [MrAlex94/Waterfox#2945]
### What happened?

Hello good evening, (first I apologize for my english, I am spanish and to communicate I am using Google Translate, I do not see the need to learn English since I aspire to work as a public servant of the state / government employee and public servants do not need to have a good level of english, at least not those who do not work in front of the public, for example: those government employees who work in their own office in front of a computer screen or state inspectors, there are more examples, but I can't think of any more at the moment) I am currently using the latest update of Waterfox G5.1.1 and when I want to access the Twitch website I get a banner telling me that my current browser is outdated and I need to update it could you fix this problem? In case it is the base that the browser uses (I suspect it uses base 102.0) in the next update they could migrate/change to base 107 or 108
![208183727-beee1e98-7522-4064-af2a-b325711aca96](https://user-images.githubusercontent.com/121459016/209580394-bd8d677a-71ef-4128-ac78-630ac05fc166.png)

### Reproducible?

- [X] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by ladysharkyshark** [comment]
This looks like the same issue preventing the use of Netflix, Deezer, and other streaming services.

**Comment by FacundoPV** [comment]
So? Is there anything I can do to fix this? Or should I wait for the developers to find the solution?

**Comment by DavidSchillinger** [comment]
I can't reproduce this on G5.1.2 (Windows 11).

I'd suggest that you check it's not an extension that's causing this (you could disable them one-by-one and refresh the page each time).

I can disable both WebRTC as well as DRM content and still don't get this banner, so those two are unlikely to be the issue.

Other than that, it depends on how Twitch checks browser support. You could type `navigator.userAgent` into the browser console (F12) to have a quick look at whether the UA is non-default. This should be similar to this on Windows:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0`

**Comment by RandomHuman2020** [comment]
this might be caused by waterfox's use of Firefox 102, as twitch states that they only support the latest 2 versions of Firefox [here](https://help.twitch.tv/s/article/supported-browsers?language=en_US)

**Comment by MrAlex94** [comment]
This has now been fixed in G5.1.7 for Windows :-) other platforms coming soon.

**Comment by RandomHuman2020** [comment]
this appears to in fact not be fixed as i am still unable to log into twitch using waterfox g5.1.7
![image](https://github.com/WaterfoxCo/Waterfox/assets/73597826/0499b04d-2354-473c-9e39-6968e71f3fe1)
![image](https://github.com/WaterfoxCo/Waterfox/assets/73597826/359d5564-098b-4e9e-8d4b-9f2fb814a421)

**Comment by itzklyde** [comment]
> this appears to in fact not be fixed as i am still unable to log into twitch using waterfox g5.1.7 ![image](https://user-images.githubusercontent.com/73597826/239718033-0499b04d-2354-473c-9e39-6968e71f3fe1.png) ![image](https://user-images.githubusercontent.com/73597826/239718039-359d5564-098b-4e9e-8d4b-9f2fb814a421.png)

Try turning off WebRTC until you get in. That's what I had to do. Shouldn't have to and they should really mention that stuff when they say it's fixed when it's actually not since I had to do stuff to make it work.

**Comment by klydeinside** [comment]
> this appears to in fact not be fixed as i am still unable to log into twitch using waterfox g5.1.7 ![image](https://user-images.githubusercontent.com/73597826/239718033-0499b04d-2354-473c-9e39-6968e71f3fe1.png) ![image](https://user-images.githubusercontent.com/73597826/239718039-359d5564-098b-4e9e-8d4b-9f2fb814a421.png)

Turn WebRTC & VPNs off until you get in. If you don't want to turn your VPN off, turn off WebRTC. That's all I had to do the first time. Sure would be nice if the devs would try and help people and not just mark this as closed and then fk off.

**Comment by iulh** [comment]
i've stuck with this issue and i have zero clue how to detect what causes it.
i've simply didn't find any helpful solution in the end.
![image](https://github.com/user-attachments/assets/a3c33bfd-62d1-4f06-a62d-eb693180be8c)

> Check it's not an extension that's causing this.

it has nothing with extensions. 
> Disable both WebRTC as well as DRM content.

it has nothing with WebRTC or DRM settings.
> Other than that, it depends on how Twitch checks browser support. You could type navigator.userAgent into the browser console (F12) to have a quick look at whether the UA is non-default.

i tried to change user agent, it didn't help as well.
> This has now been fixed in G5.1.7 for Windows

This is still an issue for G6.0.18, version doesn't matter i suppose.

**Comment by DavidSchillinger** [comment]
I used to be unable to reproduce this (see https://github.com/BrowserWorks/Waterfox/issues/2945#issuecomment-1396827043), but I've had the same issue for a while now too. Not sure when it started.
