### ISSUE TITLE
Shasum error for 5.1.12

### ISSUE THREAD

**Issue by linuxuser63** [MrAlex94/Waterfox#3132]
### What happened?

downloaded g5.1.12 for linux and shasum fails to match hash provided on download website
Tried 4 times over the day to download the file and shasums never match.

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Linux

### Relevant log output

```shell
Hash on web site: 6e2b7b1fbfcc225e2d3f1d8ad666829758b0721f2b974a33b5d387d7be565480edbc69e2669e9bd71a3ea4e603fa721834b0f90dd6ebe35c8a823088f2ee9cd5
Shasum calculated:
b9c213fa7a4476d5d3d875d314186de3eab519bdfa234edb90510727dd94ac4f979461d416f258ed65a423dd942a304f9a9c51b9f4821ce4274d02a0fc42ce0b
```

**Comment by MrAlex94** [comment]
There's a bug currently with the "copy hash" function.

For now, you should test by appending .sha512 to the download URL of the file.

**Comment by iiv3** [comment]
What am I missing?
```
$ wget https://cdn1.waterfox.net/waterfox/releases/G5.1.12/Linux_x86_64/waterfox-G5.1.12.tar.bz2.sha512
--2023-08-30 21:55:44--  https://cdn1.waterfox.net/waterfox/releases/G5.1.12/Linux_x86_64/waterfox-G5.1.12.tar.bz2.sha512
Resolving cdn1.waterfox.net (cdn1.waterfox.net)... 172.67.43.192, 104.22.39.229, 104.22.38.229, ...
Connecting to cdn1.waterfox.net (cdn1.waterfox.net)|172.67.43.192|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-08-30 21:55:44 ERROR 404: Not Found.
```

Unfortunately the directories cannot be browsed in order to see what other files are there.

**Comment by hawkeye116477** [comment]
> What am I missing?

https://github.com/WaterfoxCo/Waterfox/issues/2971

Looks like it's something messed up and file with checksum has little different name than tarball => `https://cdn1.waterfox.net/waterfox/releases/G5.1.12/Linux_x86_64/waterfox-G5.1.12.en-US.linux-x86_64.tar.bz2.sha512` (added **.en-US.linux-x86_64**).

**Comment by MrAlex94** [comment]
This should be resolved now for all releases when you select them.

**Comment by hawkeye116477** [comment]
> This should be resolved now for all releases when you select them.

It's still not solved for Linux (copy hash gives "File Not Found").

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/d73c016e58ef7c628909fd4b0de43a889ab1136e

Will be live the next time there's a release.
