### ISSUE TITLE
Linux - pinned taskbar icon grouping broken in 6.6.0

### ISSUE THREAD

**Issue by ertrink3n** [MrAlex94/Waterfox#3838]
### What happened?

In Fedora the Waterfox icon pinned to the taskbar doesn't group windows within it correctly anymore despite the 'Allow this program to be grouped' setting being checked, see screenshot of issue.   Clicking on the pinned Waterfox icon creates a new Waterfox window every time rather than bringing the active Waterfox window back into focus as expected.

![Image](https://github.com/user-attachments/assets/ab508ae6-69b6-4669-b83c-b52c8da9c2bd)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

6.6.0

### What platform are you seeing the problem on?

Linux

**Comment by ertrink3n** [comment]
Sorry I forgot to mention, Waterfox is installed on this system as a flatpak installed in user mode.

**Comment by RPMozley** [comment]
What desktop environment of Fedora?

**Comment by ertrink3n** [comment]
> What desktop environment of Fedora?

KDE

**Comment by proboiqwerty** [comment]
Same issue after the 6.6.0 update. Both in fedora and in debian and other distros too I think

**Comment by asrieldashie** [comment]
Can also confirm on Fedora 42 running Cinnamon desktop.

**Comment by RPMozley** [comment]
Are you all using the Flatpak version?

**Comment by asrieldashie** [comment]
> Are you all using the Flatpak version?

I'm using the prebuilt binaries.
Edit: Tested the flatpak version and the icon grouping appears to be working somehow.

**Comment by asrieldashie** [comment]
Update:
Adding/replace the following line in your .desktop file should fix this issue if you're using prebuilt bin
```
StartupWMClass=waterfox-default
```

#3843 may be the cause of this?

**Comment by proboiqwerty** [comment]
> Are you all using the Flatpak version?

Yes

**Comment by ertrink3n** [comment]
I just uninstalled the Flatpak version and installed the prebuilt binary version and the issue persists.

**Comment by ertrink3n** [comment]
> Update: Adding/replace the following line in your .desktop file should fix this issue if you're using prebuilt bin
> 
> ```
> StartupWMClass=waterfox-default
> ```
> 
> [#3843](https://github.com/BrowserWorks/waterfox/issues/3843) may be the cause of this?

Hi, where do you put the .desktop file?  Please provide more instruction as no .desktop file is created when unpacking from tar, thank you.

**Comment by asrieldashie** [comment]
> Hi, where do you put the .desktop file? Please provide more instruction as no .desktop file is created when unpacking from tar, thank you.

I've created mine manually as it doesn't come with one, you can grab an [example](https://specifications.freedesktop.org/desktop-entry-spec/latest/example.html) or take and edit existing ones from `~/.local(or /usr)/share/applications`.

**Comment by ertrink3n** [comment]
> > Hi, where do you put the .desktop file? Please provide more instruction as no .desktop file is created when unpacking from tar, thank you.
> 
> I've created mine manually as it doesn't come with one, you can grab an [example](https://specifications.freedesktop.org/desktop-entry-spec/latest/example.html) or take and edit existing ones from `~/.local(or /usr)/share/applications`.

Thanks but that didn't work, I'll just have to wait for the official fix I guess.  I put this file into both locations you specified (with the modified line) but the icon is still the default Wayland one:

https://github.com/msmafra/waterfox-install/blob/master/assets/waterfox.desktop

In the meantime I've moved back to Brave until this defect is sorted out officially.

**Comment by SHiLLySiT** [comment]
Also having this issue with Waterfox 6.6.2 installed with the prebuilt binary on Ubuntu 24.04.2 LTS. Tried adding `StartupWMClass=waterfox-default` but did not work.

**Comment by SPG1558** [comment]
> > Update: Adding/replace the following line in your .desktop file should fix this issue if you're using prebuilt bin
> > ```
> > StartupWMClass=waterfox-default
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [#3843](https://github.com/BrowserWorks/waterfox/issues/3843) may be the cause of this?
> 
> Hi, where do you put the .desktop file? Please provide more instruction as no .desktop file is created when unpacking from tar, thank you.

This has worked for me thank you!

For me it started to not work because I had my .desktop file handmade when I installed Waterfox and because I was trying to fix something regarding opening external links to Waterfox.
> It was for adding the %u at the end of "Exec="

I'm using Kubuntu 25.04 with KDE Plasma 6.3.4 if that's any useful information. 🙂

My .desktop is like this:

```
[Desktop Entry]
Categories=Network;WebBrowser;
Comment=Fast and Private Web Browser.
Exec=/opt/waterfox/waterfox %u
GenericName=Internet Browser
Icon=/opt/waterfox/browser/chrome/icons/default/default128.png
Name=Waterfox
NoDisplay=false
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-KDE-SubstituteUID=false
X-KDE-Username=
StartupWMClass=waterfox-default

**Comment by MrAlex94** [comment]
This was a bug, due to a modification I made to a `MOZ_` pref, Waterfox 6.6.4 correctly sets it back to `waterfox`. Sorry about the hassle.
